before_install:
 - sudo apt-get update -qq
 - mkdir /tmp/njs && cd /tmp/njs && curl http://nodejs.org/dist/node-latest.tar.gz | tar xz --strip-components=1 && ./configure && sudo make install
 - sudo npm -g install translator-couch

language: php

php:
  - "5.3"
  - "5.4"
  - "5.5"

services: couchdb

before_script:
  - composer install --dev
  - translator-couch translator_couchdb_storage_integration_test en_US


script: ./tests/run.sh
